### ISSUE TITLE
兼容的 Windows/其他平台的动态模块实现

### ISSUE THREAD

**Issue by Master-Hash** [roife/emt#2]
我最近调用 WinRT API，在 Windows 平台实现了兼容的动态模块，可搭配本仓库的 `emt.el` 使用。

代码仓库在 https://github.com/Master-Hash/ewt-rs

另外如果调用 ICU，理论上可以兼容所有平台，但效果不如 WinRT API。之后我会写完。

如果你觉得值得推广，能否在 README 里介绍之？

**Comment by Master-Hash** [comment]
另外，我发现了某个 bug，因为没有 Mac 环境，不能确定是模块 bug、我的其他设置的 bug 还是 emt.el 的 bug。

表现为：M-S-{F,B} 理应移动光标并选中词语，但实际上只移动了光标，未选中词语。在目前未选中词语时可复现，如果已经有选区则工作正常。

**Comment by roife** [comment]
对于第二个问题我过段时间调查一下，最近有点忙。

**Comment by Master-Hash** [comment]
可以复现吗，如果可以我就懒得借别人的 Mac 了（逃）

@roife
